### ISSUE TITLE
Hello i am getting this issue do you know why? 

### ISSUE THREAD

**Issue by gururespon** [Decode84/Forum#1]
![image](https://github.com/Decode84/Forum-OGUsers/assets/72622675/764aa44c-7727-4137-a23d-7a06b9ec9fb9)

when running  php artisan migrate --seed

**Comment by Decode84** [comment]
It's because you have not installed the SQL driver, the standard one being used is MySQL. You can adjust for this in the .env file.

**Comment by gururespon** [comment]
Fixed that issue, but now i get this issue 
![image](https://github.com/Decode84/Forum/assets/72622675/4150c2eb-3ff6-4601-a338-0cd06d0e7810)

**Comment by Decode84** [comment]
Minor mistake on my part. Pull the newest update and try again. 

Should be fixed here. https://github.com/Decode84/Forum/commit/b92d3b58628c7d36794e4b67f021573a8d8a0340

**Comment by gururespon** [comment]
![image](https://github.com/Decode84/Forum/assets/72622675/85a37038-612d-4a22-9388-81979b32f809)

**Comment by Decode84** [comment]
You need to enable the fileinfo extension in your PHP configuration. 

To enable the `fileinfo` extension in your PHP configuration, you can do the following:

**For Windows users:**

1. Open your `php.ini` file. You can find its location by running `php --ini` in your command prompt. 

2. Find the line `;extension=php_fileinfo.dll`

3. Uncomment it by removing the semi-colon (;) at the start, like so: `extension=php_fileinfo.dll`

4. Save the `php.ini` file and restart your web server (like Apache or Nginx) to apply the changes.

**For Linux users (e.g., Ubuntu):**

1. Open a terminal window.

2. Install the `php-fileinfo` extension by running the command: 
    ```
    sudo apt-get install php-fileinfo
    ```

3. After installation, restart your web server. If you're using Apache, you can use the command: 
    ```
    sudo service apache2 restart
    ```

4. If you're using Nginx with PHP-FPM, you can use the command: 
    ```
    sudo service php7.4-fpm restart
    ```
    (Please replace `7.4` with your actual PHP version.)

5. If the extension doesn't load or isn't installed correctly, you may need to manually enable it in your `php.ini` file (located in your PHP installation directory). Find the line `;extension=fileinfo`, uncomment it by removing the semi-colon (;), save the file, and then restart your web server.

**For MacOS users:**

If you're using Homebrew, it's as simple as:

1. Update Homebrew: 
    ```
    brew update
    ```

2. Install PHP with fileinfo:
    ```
    brew install php@7.4
    ```
    (Please replace `7.4` with your actual PHP version.)

3. After installation, restart your web server.

**Comment by Decode84** [comment]
You might need to enable some extensions in your PHP configuration. Here's how you can enable the PDO MySQL extension based on your operating system, in case you have not done so. 

**For Windows users:**

1. Open your `php.ini` file. You can find its location by running `php --ini` in your command prompt.

2. Find the lines `;extension=pdo_mysql` and `;extension=pdo` 

3. Uncomment them by removing the semi-colon (;) at the start, like so:
    ```
    extension=pdo_mysql
    extension=pdo
    ```

4. Save the `php.ini` file and restart your web server (like Apache or Nginx) to apply the changes.

**For Linux users (e.g., Ubuntu):**

1. Open a terminal window.

2. Install the `php-mysql` extension by running the command:
    ```
    sudo apt-get install php-mysql
    ```

3. After installation, restart your web server. If you're using Apache, you can use the command:
    ```
    sudo service apache2 restart
    ```

4. If you're using Nginx with PHP-FPM, you can use the command:
    ```
    sudo service php7.4-fpm restart
    ```
    (Please replace `7.4` with your actual PHP version.)

**For MacOS users:**

If you're using Homebrew, it's as simple as:

1. Update Homebrew: 
    ```
    brew update
    ```

2. Install PHP with MySQL:
    ```
    brew install php@7.4
    ```
    (Please replace `7.4` with your actual PHP version.)

3. After installation, restart your web server.

**Comment by gururespon** [comment]
Did that still not worky.

**Comment by Decode84** [comment]
Run this command, if the mysql for you don't work, you can always try out sqlite or pgsql

- php8.2-sqlite3
- php8.2-pgsql

```
sudo apt install php8.2-cli php8.2-curl php8.2-mbstring php8.2-mcrypt php8.2-xml php8.2-zip php8.2-mysql
```

**Comment by gururespon** [comment]
![image](https://github.com/Decode84/Forum/assets/72622675/30c9cf97-775b-424c-a463-9b61c5ff6626)
I am on windows btw.

**Comment by Decode84** [comment]
I have no idea about how to do it on Windows. But you can try add this ppa, this is related to Ubuntu server though. 

```
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
```

**Comment by Decode84** [comment]
Closing since no comment has been made since.
